name: 🐛 Bug report
description: Report errors or unexpected behavior
labels:
  - bug 🐛
  - unverified ⌛
body:
  - type: markdown
    attributes:
      value: Please make sure to [search for existing issues](https://github.com/jeremytammik/RevitLookup/issues?q=) before filing a new one!
  - type: input
    attributes:
      label: RevitLookup version
      placeholder: 2025.0.0
      description: Look at system Setting or About page
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: We highly suggest including screenshots and a bug report log (%LocalAppData%\Autodesk\Revit\Autodesk Revit {version}\Journals)
      placeholder: Having detailed steps helps us reproduce the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Other Software
      description: If you're reporting a bug about our interaction with other plugins, what plugins? What versions?
      placeholder: |
        PowerAutomate
        Forma
        BimTools v1.0
    validations:
      required: false
