name: Code quality

on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          args: --ide,QDNET
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}