name: Code quality

on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --baseline,qodana.sarif.json,--ide,QDNET
          pr-mode: ${{ github.event_name == 'pull_request_target' }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}